### PR TITLE
[Common][SRS] Implement Camunda Client and specify exceptions

### LINKED ISSUE #14: [Common] Implement client to communicate with Camunda through SRS
### Description

Implement client to communicate with Camunda through SRS.

### LINKED ISSUE #15: [Common] Specify exception handling process
### Description

Specify exception handling process.

### Solution

- Create class of application exception
- Add a few messages

### PR DESCRIPTION
**Pull request by GUSAR1T0**
Closes #14 and closes #15

### CODE REVIEW

File: DevTools/Common/Entities/Enums/CamundaAction.cs [hunk 1]
```diff
@@ -1,9 +1,8 @@
-using VXDesign.Store.DevTools.Common.Entities.Enums;
```
Comment (GUSAR1T0) [inline DevTools/Common/Entities/Enums/CamundaAction.cs]: Reduce codes of `Authorization` block

File: DevTools/Common/Models/Camunda/Authorization/AuthorizationGetListModels.cs [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+        [HttpQueryParameter]
+        public int? MaxResults { get; set; }
+    }
+
+    public class AuthorizationGetListResponseModel : CamundaResponseModels<AuthorizationList>
+    {
+    }
+
+    public class AuthorizationList
```
Comment (GUSAR1T0) [inline DevTools/Common/Models/Camunda/Authorization/AuthorizationGetListModels.cs]: Move entity class to another namespace

File: DevTools/Common/Models/Camunda/Authorization/AuthorizationGetListModels.cs [hunk 3]
```diff
@@ -0,0 +1,68 @@
+using System.Collections.Generic;
```
Comment (GUSAR1T0) [inline DevTools/Common/Models/Camunda/Authorization/AuthorizationGetListModels.cs:1]: Add one more example for single entity + make response as transformable (`response` => `entity`)

File: DevTools/Common/Entities/Camunda/CamundaFile.cs [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+
+        internal CamundaFile(byte[] data, string fileName, string mimeType, string encoding)
+        {
+            Data = data;
+            FileName = fileName;
+            MimeType = mimeType;
+            Encoding = encoding;
+        }
+
+        public byte[] Data { get; }
```
Comment (GUSAR1T0) [inline DevTools/Common/Entities/Camunda/CamundaFile.cs]: Move above

File: DevTools/Common/Extensions/Camunda/CamundaResponseModelExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+    {
+        internal static TModel PostHandle<TModel>(this TModel model) where TModel : ICamundaResponseModel
+        {
+            var settings = new JsonSerializerSettings
+            {
+                ContractResolver = new ResponseJsonResolver(),
+                NullValueHandling = NullValueHandling.Ignore
+            };
+
+            if (model.Status >= 400) throw CommonExceptions.SyrinxHasSentErrorResponse(model);
```
Comment (GUSAR1T0) [inline DevTools/Common/Extensions/Camunda/CamundaResponseModelExtensions.cs]: Hide magic status numbers to method/property

File: DevTools/Common/Models/Camunda/Authorization/AuthorizationGetListModels.cs (hunk 3 above)
Comment (GUSAR1T0) [reply DevTools/Common/Models/Camunda/Authorization/AuthorizationGetListModels.cs:1]: The idea has some major issues to be implemented right now, postponed
